# NOTE
# - Numbers read as a double in the program must be written to one decimal place.
# - Exponential notation must be written to one decimal place.

# computational conditions
dim: 2
particle distance: 0.01
dt: 0.001
finish time: 2.0
output interval: 0.05
CFL condition: 0.3
# numPhysicalCores: 4

# domain
domain range X: [-0.1, 0.4]
domain range Y: [-0.1, 0.35]
domain range Z: [0.0, 0.0]

# physical properties
density: 1000.0
kinematic viscosity: 1.0e-06 # If we don't write to one decimal place, it will be recognized as a string of characters.

# gravity
gravity: [0.0, -9.8, 0.0]

# effective radius (ratio to the particle distance)
effective radius ratio:
  pressure: 3.1
  viscosity: 3.1
  surface detection: 3.1

# surface detection
threshold for surface detection: 0.97

# pressure calculation
pressure stabilization:
  relaxation coefficient:
    on: True
    gamma: 0.2
  quasi compressibility:
    on: True
    compressibility: 0.45e-09
  higher order source term:
    on: False
    gamma: 1.0e-03

# collision
collision distance ratio: 0.5 # ratio to particle distance
coefficient of restitution: 0.2

# i/o
inputCsvPath: inputs/dambreak/input.csv
